version: '3'

services:

  mongodb:
    image: bitnami/mongodb:4.4
    volumes:
      - ./data/mongodb:/bitnami/mongodb
    ports:
      - '27017:27017'
    environment:
      MONGODB_ROOT_PASSWORD: super-password

  mongo-express:
    image: mongo-express
    ports:
      - '8000:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: super-password
      ME_CONFIG_MONGODB_URL: mongodb://root:super-password@mongodb:27017/