services:
  mongodb:
    image: mongo:8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=super-password
#    command:
#      - --replSet
#      - rs0
#      - --bind_ip_all
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data
#    healthcheck:
#      test: test $$(mongosh --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongodb:27017\"}]})}
#        catch(e) {rs.status().ok}") -eq 1
#      interval: 5s
#      timeout: 5s
#      retries: 10

  mongo-express:
    image: mongo-express
    ports:
      - '8000:8081'
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: super-password
      ME_CONFIG_MONGODB_URL: mongodb://root:super-password@mongodb:27017/