spring:
  data:
    mongodb:
      uri: mongodb://root:super-password@localhost:27017/simple-service?authSource=admin
      auto-index-creation: true
  session:
    mongodb:
      collection-name: user-sessions
    timeout: 30m

server:
  port: 8090

logging:
  level:
    app.shyurock: debug

springdoc:
  api-docs:
    path: /api/swagger
  swagger-ui:
    path: /api/swagger/ui.html
  paths-to-match: /api/**